"""Added shares column

Revision ID: acfe55e63063
Revises: 68a95593bd0a
Create Date: 2020-03-29 16:24:27.502539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfe55e63063'
down_revision = '68a95593bd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StockPrices',
    sa.Column('Ticker', sa.String(length=5), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=True),
    sa.Column('Volume', sa.Integer(), nullable=True),
    sa.Column('Shares', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Ticker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StockPrices')
    # ### end Alembic commands ###
